{
 "title": "Template DashBoard [${ENVIRONMENT}]",
 "tags": [
  "kubernetes",
  "prometheus",
  "uid",
  "vertx",
  "kong"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "gc_node",
    "query": "label_values(kube_node_info,node)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_created,namespace)"
   },
   {
    "name": "deployment",
    "query": "label_values(kube_deployment_status_replicas ,deployment)"
   },
   {
    "name": "kong_service",
    "query": "label_values(kong_http_status,service)"
   },
   {
    "name": "label",
    "label": "label",
    "query": "label_values(jvm_memory_used_bytes,label)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", area=\"nonheap\"},id)"
   },
   {
    "name": "kube_pod",
    "label": "Name of k8s pod",
    "query": "label_values(jvm_memory_used_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\"},kube_pod)"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Alerts History", "type": "alertlist", "gridPos": { "h": 14, "w": 6, "x": 0, "y": 1 } },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{id=\"/\"}[30s])) by (instance) / sum(machine_cpu_cores) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\"} / container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\"}) by (instance) *100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NonRunning Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!~\"Running|Succeeded\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "100*sum((node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) by (kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Storage Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(kubelet_volume_stats_capacity_bytes) by (persistentvolumeclaim) - sum(kubelet_volume_stats_available_bytes) by (persistentvolumeclaim))/sum(kubelet_volume_stats_capacity_bytes) by (persistentvolumeclaim) *100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Eventbus: pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vertx_eventbus_pending{kubernetes_namespace=~\"staging|production\"}) by (label,kubernetes_namespace)",
     "legendFormat": "{{label}} [{{kubernetes_namespace}}]"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency per Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"kong\",service=~\"staging.*|production.*\"}[1m])) by (service,le))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Time per Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"upstream\", service=~\"staging.*|production.*\"}[1m])) by (le,service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "graph",
   "description": "Number of container restarts",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"staging|production\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Node Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none", "label": "Nodes" }
     ],
     "targets": [
      { "expr": "sum(kube_node_info)", "legendFormat": "Count" }
     ]
    },
    {
     "title": "Node Pods Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "pods" }
     ],
     "targets": [
      {
       "expr": "avg(kube_node_status_allocatable_pods)",
       "legendFormat": "allocable"
      },
      {
       "expr": "sum(kube_pod_info{node=~\"$gc_node\"}) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Node CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "avg(kube_node_status_capacity_cpu_cores{node=~\"$gc_node\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(rate(container_cpu_user_seconds_total{id=\"/\", instance=~\"$gc_node\"}[30s])) by (instance)",
       "legendFormat": "used [{{instance}}]"
      }
     ]
    },
    {
     "title": "Node Disk Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "decbytes", "label": "Disk" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\", instance=~\"^$gc_node\"})  by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg(kube_node_status_capacity{resource=\"ephemeral_storage\", node=~\"^$gc_node\"})",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Node Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "decbytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "avg(node_memory_MemTotal_bytes{kubernetes_node=~\"$gc_node\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{kubernetes_node=~\"$gc_node\"}) by (kubernetes_node) - sum(node_memory_MemAvailable_bytes{kubernetes_node=~\"$gc_node\"}) by (kubernetes_node)",
       "legendFormat": "{{kubernetes_node}}"
      }
     ]
    },
    {
     "title": "Storage Disk Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "decbytes", "label": "Storage Usage" }
     ],
     "targets": [
      {
       "expr": "(sum(kubelet_volume_stats_capacity_bytes) by (persistentvolumeclaim) - sum(kubelet_volume_stats_available_bytes) by (persistentvolumeclaim))",
       "legendFormat": "usage [{{persistentvolumeclaim}}]"
      }
     ]
    },
    {
     "title": "Container Memory Requested by Node",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sort_desc(sum(kube_pod_container_resource_requests_memory_bytes) by (node) / sum(kube_node_status_allocatable_memory_bytes) by (node)) *100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Container CPU Requested by Node",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 40 },
     "targets": [
      {
       "expr": "sort_desc(sum(kube_pod_container_resource_requests_cpu_cores) by (node)  / sum(kube_node_status_allocatable_cpu_cores) by (node)) *100",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments, Pods and Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last  deployments",
     "type": "table",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sort_desc(sum((kube_deployment_created{ namespace=~\"$namespace\", deployment=~\"$deployment\"}) * 1000) by (deployment))",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "POD internal IP address",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 3 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "sum(kube_pod_info{namespace=~\"$namespace\", pod=~'$deployment.*', pod_ip!=\"\"}) by (pod_ip,pod)",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Restarts by container",
     "type": "table",
     "description": "Number of container restarts group by pod and namespace.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_restarts_total) by (container,pod,namespace)"
      }
     ]
    },
    {
     "title": "Pods per Deployment",
     "type": "graph",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\", deployment=~\"$deployment\"}) by (deployment)",
       "legendFormat": "{{ deployment }}",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Pod Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$deployment.*\"}) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Container CPU Usage Detail",
     "type": "graph",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "none", "label": "mCPU" }
     ],
     "targets": [
      {
       "expr": "sort_desc(avg(rate(container_cpu_user_seconds_total{image!=\"\",instance=~\".*\", namespace=~\"$namespace\", container_name!=\"POD\", pod_name=~\"$deployment.*\"}[30s]) * 1000) by (container_name))",
       "legendFormat": "{{ container_name }}"
      }
     ]
    },
    {
     "title": "Container Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\", pod=~\"$deployment.*\"})",
       "legendFormat": "running"
      },
      {
       "expr": "sum(kube_pod_container_status_terminated_reason{namespace=~\"$namespace\", pod=~\"$deployment.*\"}) by (reason)",
       "legendFormat": "{{reason}}"
      },
      {
       "expr": "sum(kube_pod_container_status_waiting_reason{namespace=~\"$namespace\", pod=~\"$deployment.*\"}) by (reason)",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Container Memory Usage Detail",
     "type": "graph",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(avg(container_memory_usage_bytes{image!=\"\",instance=~\"$gc_node\", namespace=~\"$namespace\", container_name!=\"POD\", pod_name=~\"$deployment.*\"}) by (container_name))",
       "legendFormat": "{{ container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kong",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "OPS per service ($kong_service)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_status{service=~\"$kong_service\", service=~\"$namespace.*\"}[1m])) by (service)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "DB reachability",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kong_datastore_reachable)*100/count(kong_datastore_reachable)"
      }
     ]
    },
    {
     "title": "Upstream Time across per service ($kong_service)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"upstream\", service=~\"$kong_service\", service=~\"$namespace.*\"}[1m])) by (le,service))",
       "legendFormat": "p99-{{service}}"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency per Service ($kong_service)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99,sum(rate(kong_latency_bucket{type=\"kong\", service=~\"$kong_service\", service=~\"$namespace.*\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      }
     ]
    },
    {
     "title": "Bandwidth per Service ($kong_service)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_bandwidth{service=~\"$kong_service\", service=~\"$namespace.*\"}[1m])) by (type,service)",
       "legendFormat": "{{type}}_{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Vertx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "OPS per label ($label) and response code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "round(sum(rate(vertx_http_server_requestCount_total{label!=\"\", label=~\"$label\", kubernetes_namespace=~\"$namespace\"}[1m])) by (label,code,kubernetes_namespace), 0.001)",
       "legendFormat": "{{code}} [{{label}}]  [{{kubernetes_namespace}}]"
      }
     ]
    },
    {
     "title": "HTTP Server bytes sent/received per label ($label)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vertx_http_server_bytesSent_bucket{label!=\"\", label=~\"$label\", kubernetes_namespace=~\"$namespace\"}[1m])) by (label,kubernetes_namespace)",
       "legendFormat": "sent [{{label}}]  [{{kubernetes_namespace}}]"
      },
      {
       "expr": "sum(rate(vertx_http_server_bytesReceived_bucket{label!=\"\", label=~\"$label\", kubernetes_namespace=~\"$namespace\"}[1m])) by (label,kubernetes_namespace)",
       "legendFormat": "received  [{{label}}]  [{{kubernetes_namespace}}]"
      }
     ]
    },
    {
     "title": "Eventbus processing time per label ($label)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(vertx_eventbus_processingTime_seconds_bucket{label=~\"$label\", kubernetes_namespace=~\"$namespace\"}[1m])) by (le,label,kubernetes_namespace))",
       "legendFormat": "{{label}} [{{kubernetes_namespace}}]"
      }
     ]
    },
    {
     "title": "Eventbus: handlers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 11, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vertx_eventbus_handlers{label=~\"$label\", kubernetes_namespace=~\"$namespace\"}) by (label,kubernetes_namespace)",
       "legendFormat": "{{label}} [{{kubernetes_namespace}}]"
      }
     ]
    },
    {
     "title": "Eventbus: pending",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 17, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vertx_eventbus_pending{label=~\"$label\", kubernetes_namespace=~\"$namespace\"}) by (label,kubernetes_namespace)",
       "legendFormat": "{{label}}  [{{kubernetes_namespace}}]"
      }
     ]
    },
    {
     "title": "EventBus Addresses",
     "type": "table",
     "gridPos": { "h": 14, "w": 9, "x": 0, "y": 18 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "sum(vertx_eventbus_handlers{label=~\"$label\",address!=\"\", kubernetes_namespace=~\"$namespace\"}) by (address, kubernetes_namespace)",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Response time by label ($label)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum{label!=\"\",label=~\"$label\", kubernetes_namespace=~\"$namespace\"}[1m])) by (label,kubernetes_namespace) / sum(irate(vertx_http_server_responseTime_seconds_count{label!=\"\",label=~\"$label\", kubernetes_namespace=~\"$namespace\"}[1m])) by (label,kubernetes_namespace)",
       "legendFormat": "{{label}}  [{{kubernetes_namespace}}]"
      }
     ]
    },
    {
     "title": "Response time by label and path ($label)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vertx_http_server_responseTime_seconds_sum{label!=\"\",path!=\"\",label=~\"$label\", kubernetes_namespace=~\"$namespace\"}[1m])) by (path,label,kubernetes_namespace) / sum(irate(vertx_http_server_responseTime_seconds_count{label!=\"\",label=~\"$label\",path!=\"\", kubernetes_namespace=~\"$namespace\"}[1m])) by (path,label,kubernetes_namespace)",
       "legendFormat": "{{label}}{{path}}  [{{kubernetes_namespace}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", area=\"heap\", kube_pod=~\"$kube_pod\"}) by (label, kubernetes_namespace, kube_pod)",
       "legendFormat": "{{label}} used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", area=\"heap\", kube_pod=~\"$kube_pod\"}) by (label, kubernetes_namespace, kube_pod)",
       "legendFormat": "{{label}} committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", area=\"heap\", kube_pod=~\"$kube_pod\"}) by (label, kubernetes_namespace, kube_pod)",
       "legendFormat": "{{label}} max"
      }
     ]
    },
    {
     "title": "Memory Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", area=\"nonheap\", kube_pod=~\"$kube_pod\"}) by (label, kubernetes_namespace, kube_pod)",
       "legendFormat": "{{label}} used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", area=\"nonheap\", kube_pod=~\"$kube_pod\"}) by (label, kubernetes_namespace, kube_pod)",
       "legendFormat": "{{label}} committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", area=\"nonheap\", kube_pod=~\"$kube_pod\"}) by (label, kubernetes_namespace, kube_pod)",
       "legendFormat": "{{label}} max"
      }
     ]
    },
    {
     "title": "Memory Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", kube_pod=~\"$kube_pod\"}) by (label,kubernetes_namespace, kube_pod)",
       "legendFormat": "{{label}} used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", kube_pod=~\"$kube_pod\"}) by (label,kubernetes_namespace, kube_pod)",
       "legendFormat": "{{label}} committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", kube_pod=~\"$kube_pod\"}) by (label,kubernetes_namespace, kube_pod)",
       "legendFormat": "{{label}} max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\", kube_pod=~\"$kube_pod\"}",
       "legendFormat": "[{{label}}] used"
      },
      {
       "expr": "jvm_memory_committed_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\", kube_pod=~\"$kube_pod\"}",
       "legendFormat": "[{{label}}] commited"
      },
      {
       "expr": "jvm_memory_max_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\", kube_pod=~\"$kube_pod\"}",
       "legendFormat": "[{{label}}] max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\", kube_pod=~\"$kube_pod\"}",
       "legendFormat": "[{{label}}] used"
      },
      {
       "expr": "jvm_memory_committed_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\", kube_pod=~\"$kube_pod\"}",
       "legendFormat": "[{{label}}] commited"
      },
      {
       "expr": "jvm_memory_max_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\", kube_pod=~\"$kube_pod\"}",
       "legendFormat": "[{{label}}] max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\", kube_pod=~\"$kube_pod\"}",
       "legendFormat": "[{{label}}] used"
      },
      {
       "expr": "jvm_memory_committed_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\", kube_pod=~\"$kube_pod\"}",
       "legendFormat": "[{{label}}] commited"
      },
      {
       "expr": "jvm_memory_max_bytes{label=~\"$label\", kubernetes_namespace=~\"$namespace\", id=~\"$jvm_memory_pool_heap\", kube_pod=~\"$kube_pod\"}",
       "legendFormat": "[{{label}}] max"
      }
     ]
    },
    {
     "title": "GC Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{label=~\"$label\", kubernetes_namespace=~\"$namespace\", kube_pod=~\"$kube_pod\"}[1m])",
       "legendFormat": "{{label}} {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "GC Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{label=~\"$label\", kubernetes_namespace=~\"$namespace\", kube_pod=~\"$kube_pod\"}[1m])/rate(jvm_gc_pause_seconds_count{label=~\"$label\", kubernetes_namespace=~\"$namespace\", kube_pod=~\"$kube_pod\"}[1m])",
       "legendFormat": "{{label}} avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{label=~\"$label\", kubernetes_namespace=~\"$namespace\", kube_pod=~\"$kube_pod\"}",
       "legendFormat": "{{label}} max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "GC Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{label=~\"$label\", kubernetes_namespace=~\"$namespace\", kube_pod=~\"$kube_pod\"}[1m])",
       "legendFormat": "{{label}} allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{label=~\"$label\", kubernetes_namespace=~\"$namespace\", kube_pod=~\"$kube_pod\"}[1m])",
       "legendFormat": "{{label}} promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Topics Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "avg(kafka_log_Log_LogEndOffset_Value{topic=~\"ui_.*\"}) by (topic)"
      },
      {
       "expr": "avg(kafka_log_Log_Size_Value{topic=~\"ui_.*\"}) by (topic)"
      }
     ]
    },
    {
     "title": "ConsumerGroup status ",
     "type": "table",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "sum(kafka_consumer_group_offset{topic=~\"ui_.*\"}) by (topic,name)"
      },
      {
       "expr": "sum(kafka_consumer_group_rep_lag{topic=~\"ui_.*\"}) by (topic,name)"
      }
     ]
    }
   ]
  }
 ]
}